version: 2.1
  
setup: true
 
orbs:
  continuation: circleci/continuation@0.1.2
 
jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - run: echo "sample build job"
  setup: 
    docker:
     - image: cimg/base:2021.07 
    steps:
      - checkout
      - run:
          name: Create parameters to pass to continuation config
          command: |
            # create parameters json to pass to continuation workflow
            json=$(cat \<<EOD
             { "samplekey": "samplevalue"}
            EOD)
            echo $json >> /home/circleci/test.json

      - run: cat /home/circleci/test.json
      - continuation/continue:
          configuration_path: ".circleci/continuation-config.yml"
          parameters: /home/circleci/test.json

workflows:
  setup:
    jobs:
      - build
      - setup:
          requires:
            - build
