version: 2.1
  
parameters:
  samplekey:
    type: string
    default: ""

jobs:
  job2:
    docker:
      - image: cimg/base:2021.07
    steps:
      - echo "job2"
  job1:
    docker:
      -  image: cimg/base:2021.07
    steps:
      - run: 
          name: Verify parameter was passed correctly
          command: echo << pipeline.parameters.samplekey >>
          
workflows:
  workflow1:
    jobs:
      - job1
      - job2:
          requires:
            - job1
